name: Deploy

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
  push:
    branches:
      - main
      - styling-timeline-feature

jobs:
  deploy:
    name: "Deploy to VPS"
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' || github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'styling-timeline-feature' || github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'push' && github.ref == 'refs/heads/styling-timeline-feature'
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy-key.pem
          chmod 600 ~/.ssh/deploy-key.pem
          cat >> ~/.ssh/config <<END
          Host my-vps
            HostName ${{ secrets.SSH_IP }}
            User ${{ secrets.SSH_USER }}
            IdentityFile ~/.ssh/deploy-key.pem
            StrictHostKeyChecking no
          END

      - name: Deploy site
        run: ssh my-vps '~/redeploy-site.sh'

    env:
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_IP: ${{ secrets.SSH_IP }}