name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, closed]

jobs:
  test:
    runs-on: ubuntu-20.04
    name: Run Tests
    env:
      TESTING: true
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' || github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6.8'

      - name: Setup Python Virtual Environment
        run: python -m venv python3-virtualenv

      - name: Install Dependencies
        run: python3-virtualenv/bin/pip install -r requirements.txt

      - name: Grant Script Permission
        run: chmod +x run_test.sh

      - name: Run Tests
        run: ./run_test.sh