name: Run Tests

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04
    name: Run Tests
    env:
      TESTING: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6.8'

      - name: Setup Python Virtual Environment
        run: python -m venv python3-virtualenv

      - name: Install Dependencies
        run: python3-virtualenv/bin/pip install -r requirements.txt

      - name: Grant Script Permission
        run: chmod +x run_test.sh

      - name: Run Tests
        run: ./run_test.sh